// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFmME_rn5-M_fh-2kuldky2hIva0U7JYA',
    appId: '1:378920529180:web:a0832298f2fcc178501ed9',
    messagingSenderId: '378920529180',
    projectId: 'coordinate-app-5eda7',
    authDomain: 'coordinate-app-5eda7.firebaseapp.com',
    storageBucket: 'coordinate-app-5eda7.firebasestorage.app',
    measurementId: 'G-22VG49WSRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMMZq58mUUqZAZM1M_BK545w6O9TRXFWg',
    appId: '1:378920529180:android:c6307581763f751a501ed9',
    messagingSenderId: '378920529180',
    projectId: 'coordinate-app-5eda7',
    storageBucket: 'coordinate-app-5eda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLHKXnS9qgql_G0fuvKN6sy9lc6mKCTe0',
    appId: '1:378920529180:ios:88b2dd0c519f0e3b501ed9',
    messagingSenderId: '378920529180',
    projectId: 'coordinate-app-5eda7',
    storageBucket: 'coordinate-app-5eda7.firebasestorage.app',
    iosBundleId: 'com.example.coordinateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLHKXnS9qgql_G0fuvKN6sy9lc6mKCTe0',
    appId: '1:378920529180:ios:88b2dd0c519f0e3b501ed9',
    messagingSenderId: '378920529180',
    projectId: 'coordinate-app-5eda7',
    storageBucket: 'coordinate-app-5eda7.firebasestorage.app',
    iosBundleId: 'com.example.coordinateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFmME_rn5-M_fh-2kuldky2hIva0U7JYA',
    appId: '1:378920529180:web:07010a10c92f04b7501ed9',
    messagingSenderId: '378920529180',
    projectId: 'coordinate-app-5eda7',
    authDomain: 'coordinate-app-5eda7.firebaseapp.com',
    storageBucket: 'coordinate-app-5eda7.firebasestorage.app',
    measurementId: 'G-0DV1QGWLW1',
  );
}
